### ISSUE TITLE
Get going problems

### ISSUE THREAD

**Issue by xendk** [stevenremot/ede-php-autoload#10]
Hi,

I've been experimenting with @jorissteyn's semantic-php and ede-php-autoload to see how far I could push Emacs towards the next level in PHP development (we're a couple of Emacs heads defending our turf against the local PHPStorm users. My colleague is the drupal-mode maintainer, and now Drupal 8 is released we start missing better OO stuff).

semantic-php works for things in the same buffer, and as far as I understand, ede-php-autoload is the next step. But I can't really figure it out.

I have ede-php-autoload-mode activated, and a buffer from a simple composer project. As I understand it, it should sniff out where to find classes from the composer.json, but semantic-complete-analyze-inline doesn't "get" anything not defined in the same file. I've tried with master and the #5-type-completion-support branch, without much luck...

I'm a bit at a loss as to how to debug my troubles, or whether I'm just expecting something it can't do yet?

**Comment by stevenremot** [comment]
Hi,

> we're a couple of Emacs heads defending our turf against the local PHPStorm users.

I'm in the same situation at my job, except I'm the only Emacs user!


> semantic-php works for things in the same buffer, and as far as I understand, ede-php-autoload is the next > step. But I can't really figure it out.

> I have ede-php-autoload-mode activated, and a buffer from a simple composer project. As I understand it, > it should sniff out where to find classes from the composer.json, but semantic-complete-analyze-inline doesn't "get" anything not defined in the same file. I've tried with master and the #5-type-completion-support branch, without much luck...

> I'm a bit at a loss as to how to debug my troubles, or whether I'm just expecting something it can't do yet?

Basically, ede-php-autoload provides APIs other packages can consume to get a mapping between fully qualified names and class names, but won't give auto-completion and "jump to definition" features to the end user out of the box.

For example, @jorissteyn 's semantic-php package could in the future detect which classes are used in the current buffer, and then ask semanticdb to find the class. If ede-php-autoload is installed, this request will be handled by the ede-php-autoload's semanticdb backend, which will find the class definition file and return its semantic tags. Then semantic-php will use these tags to provide the features you want.

For now I think semantic-php does not implement this. Statically finding all classes used in a PHP code is actually far from trivial. This seems to be in its first milestone though.

Do you need more details or is it all clear to you ?

**Comment by xendk** [comment]
Ah, yes, that clears things up a bit. A better idea of were to look at least.

I think I'll try to semantic-php up a bit, to see if I can get that working. But I'm pretty newbie in that department. I hope it shouldn't be necessary to figure out all classes for the first stab, but just wire into the completion function to get the right file from ede-php-autoload, and have semantic-php parse it to figure out what completions there are, for vars where we have a typehint. Something to start with at least.

I think that basic completion, even if it doesn't work with the more advanced uses of namespaces would quickly increase the number of people playing around with it.

**Comment by stevenremot** [comment]
Good luck! There have been some discussions on this subject on the Emacs PHP mailing list of you are interested.
