### ISSUE TITLE
Issues with autodetection

### ISSUE THREAD

**Issue by xendk** [stevenremot/ede-php-autoload#11]
Seems that I've gotten somewhere with the completion code.

However, I ede-php-autoload doesn't seem to be able to detect a composer project automatically? It only wworks when I define it with ede-php-autoload-project.

What should I look for?

**Comment by stevenremot** [comment]
Nice job for the completion code! Which cases does it handle for now?

`ede-php-autoload` uses the EDE project detection mechanism to be able to automatically detect `composer.json` files and setup an ede-php-autoload project for it. I see two main reasons it may not work as expected:

* Did you enable EDE with `(global-ede-mode 1)` ? I think I have neglected its importance in the project detection code. If this is the source of the problem I will add an instruction about it in the README.
* Are all your project's autoload in the `composer.json`? Some projects only list dependencies in it and use another autoload system for their own classes. In this case you have to declare your project by hand.

**Comment by xendk** [comment]
Well, it works for completing menbers on typehinted arguments and $this.  If/when semantic-php supports the /* @var <type> */ hints, it should work on those vars too.

I enable global-ede-mode togeter with ede-php-autoload-mode in the :init portion of a use-package, so it should be enabled.

Everything is loaded through composer, do anyone do anything else these days? The ede-php-autoload-project that works doesn't define anything else than name and a file that's basically the entrypoint (it's a simple shell command).

I'll commit my (small changes) to a fork so I can eventually make a PR, you can check it out if want.

**Comment by xendk** [comment]
Current work here: https://github.com/xendk/semantic-php/tree/completion

**Comment by stevenremot** [comment]
I see you have generated include tags for use statements. If I remember correctly @trashofmasters and I also tried this method in our own works, but actually there are a lot of cases we couldn't handle properly with just this, like using fully-qualified-names directly without use statements, using class names relative to the current namespace, or also use statements that does not refer to a class, but are just used to shorten a namespace.

In my case I started to generated include tags not at use statements, but when I see some class is used in the file (for example, if the class defined in the file is extending another one, I added an include tag to the superclass). I don't know what Andrea did after we talked about this.

> I enable global-ede-mode togeter with ede-php-autoload-mode in the :init portion of a use-package, so it should be enabled.

To bad, I hoped this was the problem. Could you comment your manual project definition, go to a file in your project, and run `ede-adebug-project` ? This will tell us if the whole project detection has failed, or only the composer parsing part.

> Everything is loaded through composer, do anyone do anything else these days?

Yes :-) . Some frameworks have their own autoload system, so sometimes you have to choose.

**Comment by xendk** [comment]
I suspected that include alone wouldn't do it, but the basic use statement *is* a, complicated, include statement.

That being said, the result doesn't exactly overwhelm me. If starting up with a clean semanticdb cache, trying to complete will load all the use'd files and scan them, apparently recursively. I tried with Drupal's BlockBase, and that left me with 44 new files in the semantic cache. 

That is pretty inefficient, as in most cases we'd know which file to load for the definition of a class/interface. 

But I can understand that semantic can't do much better at the moment, as there's nothing that tells it what belong to which file. I haven't got enough insight into the real workings of semantics completion to figure out if it would be smart enough to only load the needed files if just told which it is (which I hope),or whether that would require more custom code.

I was thinking that the brute force approach might serve as a backup for something smarter.

I got the idea for the simple include by looking at Andreas implementation.

Have an example of the "shorten a namespace" case?

`ede-adebug-project` without the project gives me nothing on M-x. Running it with M-: returns nil.. And with the project defined it gives me `ede-adebug-project: Symbol's function definition is void: data-debug-insert-object-slots`

> Some frameworks have their own autoload system, so sometimes you have to choose.

Come to think of it, Drupal is probably one. While it uses standard PSR autoloaders, it does use a bit of hackey to seperate the project composer.json from the Drupal core composer.json. We'll be at least a few that'll want to get ede-autoload to handle that case down the line.

**Comment by stevenremot** [comment]
I think the problem with include statements is that it does not really reflect the way PHP load its classes. Of course it should be possible to generate include statements for every class used in a file, but as PHP class loading is totally dynamic this makes this analyze quite difficult. When the bases of Joris' semantic-php package are done (basically when braceless namespaces are supported), I want to try overloading `semantic-ctxt-scoped-types` to load just the class definition needed for the current completion / jump request. This seems to be more like PHP operates, so this may be easier. The drawback is that it cannot benefit from semantic optimizations like the typecache.

> Have an example of the "shorten a namespace" case?

For example, in some Zend Framework code that creates some complex SQL queries, you may have:

```php
<?php

use Zend\Db\Sql;

// Later in the code...

$select = new Sql\Select(/* ... */);

// ...

$insert = new Sql\Insert(/* ... */);
```

You don't want to write the whole namespace to type each time, but it is still interesting to keep a namespace to make things clear / avoid collisions, etc...

> ede-adebug-project without the project gives me nothing on M-x. Running it with M-: returns nil..

OK, so the project object has not been created at all. It's like the `ede-project-add-autoload` form has not been executed at all. Would you mind showing me the part of your configuration that setup all this stuff please? Also, I can't remember if you told me your Emacs and CEDET version.

> ede-adebug-project: Symbol's function definition is void: data-debug-insert-object-slots

This must be an issue with some library (`eieio-datadebug`) not loading, but we may not need to solve it now :-D . If we can get the same result without the project defined by hand this will be a huge step forward.

**Comment by trashofmasters** [comment]
> You don't want to write the whole namespace to type each time, but it is still interesting to keep a namespace to make things clear / avoid collisions.

I don't remember if there's already something in Semantic catering for this, but if not it should be fine to keep track of the current namespace in a buffer variable.

> I think the problem with include statements is that it does not really reflect the way PHP load its classes.

Agreed, also if you're referring to correctly qualifying names in a buffer so *then* it's possible to find its class/tag table then I think that emitting some more `type` and `alias` tags really helps Semantic get a better picture of what and where are the real types used in a buffer.

> Of course it should be possible to generate include statements for every class used in a file, but as PHP class loading is totally dynamic this makes this analyze quite difficult. 

This is exactly the approach I took in one of my attempts to solve the problem of telling Semantic how to resolve the name `Sql\Select` in the context of a `use Zend\Db\Sql`. I used a parser which emitted `type` or `alias` tags upon encounter of any fully, or partially, qualified names. 

The technique, which involved the use of `semantic-analyze-dereference-metatype` to resolve `Sql\Select` into `Zend\Db\Sql\Select` via the `alias` tags, had its merits but complicated the grammar with long inline actions (which could be cleaned up with grammar macros).

Anyway, I'm digressing so if you want to know more about all the things I couldn't do myself in that experiment we can discuss on the other Emacs PHP mailing list.

**Comment by xendk** [comment]
Aah, relative classes, yes.

Ah yes, `semantic-ctxt-scoped-types` is a pretty important function to
implement. Interesting that it mostly works without.

I still think that include tags should be generated by something, as
it seems to be the only way to tell Semantic to load another file for
definition of something (rather that doing it yourself and the
assorted glue code), but it may be that use (and other constructs that
basically trigger the autoloader) should just emit a type tag for the
class/interface, and the include tag is generated later.

```
GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.14.9) of 2015-03-21 on kissel, modified by Debian
```

```
CEDET Version:	2.0
Requested	File		Loaded
Package		Version		Version		Version
----------------------------------------------------------
cedet:          2.0     nil     ok
eieio:          1.4     nil     ok
semantic:       2.2     nil     ok
srecode:        1.2     nil     Not Loaded
ede:            1.2     nil     ok

```

> I think that emitting some more type and alias tags

Yeah, I figure getting everything tagged up properly will go a long
way. I haven't quite gotten my head around alias tags yet, though?

I have been through tag collectors during my four day Reading Of The
Source, but haven't quite wrapped my head around it.

I figure I have to dig around the code more in order to properly grok
what's going on.

**Comment by stevenremot** [comment]
@xendk , I had a look at your dotemacs repository, but I could not find the moment you initialize ede. Is this change only local for now ?

**Comment by xendk** [comment]
Yeah, only local. The repo always lags behind.

I forgot to add it to the comment, I surely intended to:

```
(use-package ede-php-autoload-mode
  :commands ede-php-autoload-mode
  :load-path "~/.emacs.d/ede-php-autoload/"
  :init (progn
          (add-hook 'php-mode-hook 'global-ede-mode)
          (add-hook 'php-mode-hook 'ede-php-autoload-mode)
          
          )
  :config (ede-php-autoload-project "My project"
                                    :file "/home/xen/dev/proctor/proctor")
  )
```

And semantic later:

```
(use-package semantic-php
  :load-path "~/.emacs.d/semantic-php/"
  :init (progn (load "~/.emacs.d/semantic-php/loaddefs.el")
               (add-hook 'php-mode-hook #'semantic-mode))
  :config (add-to-list 'company-semantic-modes 'php-mode)
  )
```

Though that shouldn't have much to do with it.

**Comment by stevenremot** [comment]
Would you mind trying to call `global-ede-mode` directly like this:

```emacs-lisp
(use-package ede-php-autoload-mode
  :commands ede-php-autoload-mode
  :load-path "~/.emacs.d/ede-php-autoload/"
  :init (progn
          (global-ede-mode 1)
          (add-hook 'php-mode-hook 'ede-php-autoload-mode)

          )
  )
```
I wonder if it may be an issue about the argument sent to `global-ede-mode` (looking at the doc it should be ok), if it should be called as soon as possible.

**Comment by xendk** [comment]
I'll try later this evening.

**Comment by xendk** [comment]
Nope, no difference.

Messing about, it seems that it doesn't actually look for composer.json recursively. The documentation of `ede-project-autoload` would lead you to expect that it does when :proj-root is unset, but working my way downwards from `ede-initialize-state-current-buffer`, I haven't been able to find the spot where it should do it.

From my tracking about, I'm lead to believe that setting :proj-root-dirmatch to ".*" and :proj-root to a function that scans dirs downwards for composer.json, and returns the dirname of the first, should do the trick. It's far too late for me to try it out now, and I'm unlikely to find the time for it until some time next week.

**Comment by stevenremot** [comment]
I will take a look at this too when I have some more time to spend on it, but I think the ERT tests for composer projects would fail if EDE did not try to detect project file in parent directories.

**Comment by xendk** [comment]
Well, as I read ede-php-autoload-composer-test.el and define-class-definition-test, it tests with "main.php" in the root of the project.

If I change it ro "test/main.php" in ede-php-autoload-composer-test.el, the tests still pass just fine, but when I do the same to define-class-definition-test, all the composer tests fail. I don't think they should?

**Comment by stevenremot** [comment]
Hi @xendk ,

Sorry for taking so much time to look at it, I just totally forgot this issue!

I came to the same conclusion than you, and specified a `:proj-root` function to my `ede-project-autoload` and I could make the tests run again.

I created the PR #12 so that you can take a look at the code, and more importantly tell me if this solves your problem. This will be merged as soon as you validate it.

Again, sorry for the long delay!

**Comment by xendk** [comment]
I think it's working? I'm getting the `ede-adebug-project: Symbol's function definition is void: data-debug-insert-object-slots` error without having to define the project.

Ah, evaling (ede-current-project) gives me:

```
[object ede-php-autoload-project "PHP Autoload: /home/xen/dev/proctor/" nil "Untitled" "1.0" "/home/xen/dev/proctor/" 4694541 "/home/xen/dev/proctor/composer.json" nil nil ([object ede-php-autoload-target "/home/xen/dev/proctor/src/" nil "src" "/home/xen/dev/proctor/src/" nil nil #0]) ...]
```

Which looks pretty good to me.

**Comment by stevenremot** [comment]
That looks good, yes! I'm merging the PR and closing this issue.
