### ISSUE TITLE
Double backslahses in features

### ISSUE THREAD

**Issue by xendk** [stevenremot/ede-php-autoload#20]
Minor thing, but it bit me because I got burned on it in my own tests.

In features it's not necessary to double backslashes, but for the current tests it happens to work as the namespaces are toplevel.

**Comment by stevenremot** [comment]
Do you have an example please? I don't fully understand the issue

**Comment by xendk** [comment]
Here: https://github.com/stevenremot/ede-php-autoload/blob/master/features/ede-php-autoload-composer.feature#L23

It works because `MultiDirNs` is the namespace registered, and the autoloader only looks to see if it's a prefix of the requested class. If the namespace was `MultiDirNs\SubNs` and the class in that line was `"MultiDirNs\\SubNs\\TheClass1"` it would fail, as the namespace registered isn't a prefix of the requested class.

The backslashes need to be escaped with a backslash in Emacs strings, but not in feature file placeholders.

I only realized the mistake after adding debugging to the class loader and seeing the class name as `"Ns\\\\Class"` (that is, Emacs escaping the double backslash).

Hope that was more clear.

**Comment by stevenremot** [comment]
Oh I understand now ! I will take care of it, thanks !
