### ISSUE TITLE
Problems with nested composer files

### ISSUE THREAD

**Issue by xendk** [stevenremot/ede-php-autoload#24]
When opening files from a vendor package which has a `composer.json`, it creates a new ede project in the vendor project.

This causes the rest of the main project to become "invisible" to ede-php-autoload, which is a problem.

I've tried making `ede-php-autoload-proj-root` return the topmost `composer.json`, but it doesn't seem to be called (or somethings messing with me).

Or perhaps it's not creating a new project, but the vendor `composer.json` is confusing it somehow? (yeah, it's getting late here).

(side note, I've grown rather fond of https://github.com/jorgenschaefer/emacs-buttercup , so much that I've rewritten `ede-php-autoload-drupal`s tests in it)

**Comment by stevenremot** [comment]
I'm trying to reproduce the issue, but for now I didn't get any convincing result. Here is my current test for the bug:

```gherkin
Scenario: Open a file in the vendor directory
  Given I visit "vendor/third-party/third-party/src/ThirdClass.php" in project "with-composer"
  And I visit "src/main.php" in project "with-composer"
  Then the class "Psr0Ns_TheClass" should be detected in "src/Psr0Ns/TheClass.php"
```

It passes. Am I missing something?

(Yeah buttercup looks more powerful than ERT! But for functional tests I'm still a big fan of cucumber tests)

**Comment by xendk** [comment]
*checks something*

Aha, ordering of opened files are important. If a file from the "main" project is loaded first, the main project is detected and the sub-project file is considered to belong to the main project. But if the sub-project file is opened first, the sub-projects `composer.json` is found first and the sub-project gets it's own project (and opening a file in the main project later probably just makes a new project).

That can be a bit unhandy.

**Comment by stevenremot** [comment]
I agree. I will see if I can detect the topmost `composer.json` as you suggested.

**Comment by xendk** [comment]
(oh, and I agree that buttercup and ecukes is for different things)

**Comment by stevenremot** [comment]
Hey @xendk ! I think I solved the issue in the commit https://github.com/stevenremot/ede-php-autoload/commit/414971d042a1b9921a1ce702e9fd5d36c1da7298 . I will merge the branch in master when I have your approval.

**Comment by xendk** [comment]
:+1: My own test passed as soon as I checked out the branch.

**Comment by stevenremot** [comment]
Nice ! I merged the branch, so I close this issue now.
