### ISSUE TITLE
Cannot resolve file name for classes under PSR-0 + target-dir

### ISSUE THREAD

**Issue by trashofmasters** [stevenremot/ede-php-autoload#3]
I have [written a function to open the source of a use statement](https://github.com/trashofmasters/.emacs.d/blob/master/modules/ofc-php-tags.el) that uses your function `ede-php-autoload-find-class-def-file` to get the file name.

I immediately noticed that it worked fine with Larave's PSR-4 `Illuminate` classes but not with earlier versions of components from both the Zend and Symfony frameworks.

Those packages still use the PSR-0 autoloader along with a [`target-dir`](https://getcomposer.org/doc/04-schema.md#target-dir) declaration in the composer.json file [[1,2, 3](https://gist.github.com/trashofmasters/be9d38c1c8450adf2086)] and they all fail the file resolution with a resulting `nil`.

I have [hacked](https://github.com/stevenremot/ede-php-autoload/compare/master...trashofmasters:resolve-class-prefix) the function to load those packages as well, but it's obviously far from acceptable, since the code is making assumptions about a non-standard structure that changes from package to package, and is untested.

I haven't had the time to work with the ede-php-autoload functions that operate on the composer file, but I think that a fix to this problem would involve using the target-dir attribute to reconstruct the path in `ede-php-autoload-find-class-def-file`.

As a sidenote, I wasn't able to run `make test` properly as it ends with an error, but them tests all pass when run interactively with `ert`.

**Comment by stevenremot** [comment]
Hi @trashofmasters,

thanks for the bug report! The composer configuration is only used at the project's instanciation. It is parsed, and then composer autoload information is merged with the hand-defined one. I think we can support this `target-dir` attribute at this time, by using it to generate the autoload paths. I will write a corresponding test case and fix it.

Can you show your error message please ? That's bad if the test script only works on my machine.

**Comment by stevenremot** [comment]
I wrote a [test case](https://github.com/stevenremot/ede-php-autoload/commit/fedcd8b562fb10940079dfd9501ddad21b4303b8) for this issue. It seems conform to the specification of `target-dir`. Do you agree ?

Regarding How the issue can be solved, this `target-dir` allows the third-party package to be installed deeper in `vendor`, so the way I currently detect the composer files in vendor won't work. I'm wondering if it wouldn't be better to get dependencies' information using `composer.lock`file instead of sniffing each dependency's `composer.json`file. This would be more efficient and simplify the code a bit. I think I will give it a try.

**Comment by trashofmasters** [comment]
I have checked out the branch `#1-support-target-dir` and `make test` now works :+1: At the bottom of this comment you'll find the test failure log. Thanks very much for sorting out the testing groundwork.

> I'm wondering if it wouldn't be better to get dependencies' information using composer.lock file instead of sniffing each dependency's composer.json file. This would be more efficient and simplify the code a bit. I think I will give it a try.

I think you are absolutely spot on, it's should be far easier to read the `composer.lock` file as opposed to scanning the `vendor` directory tree to collect all `composer.json` files.

When the lock file is present we should be able to get the full dependency tree in one shot, otherwise we'll have to notify the user to run `composer update` on their console.


```
test/test-helper.el: Obsolete name arg "Without composer" to constructor ede-php-autoload-project
......Test ede-php-autoload-composer-find-with-target-dir backtrace:

  (if (unwind-protect (setq value-67167 (apply fn-67165 args-67166)) (
  (let (form-description-67169) (if (unwind-protect (setq value-67167
  (let ((value-67167 (quote ert-form-evaluation-aborted-67168))) (let
  (let ((fn-67165 (function string=)) (args-67166 (list "/Users/andrea
  (save-current-buffer (set-buffer (find-file "/Users/andreaturso/.ema
  (closure (t) nil (save-current-buffer (set-buffer (find-file "/Users
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test ede-php-autoload-composer-find-with
  ert-run-or-rerun-test([cl-struct-ert--stats (and t) [[cl-struct-ert-
  ert-run-tests((and t) (lambda (event-type &rest event-args) (cond ((
  ert-runner/run-tests-batch((and t))
  (let ((stats (ert-runner/run-tests-batch selector))) (kill-emacs (if
  ert-runner/run-tests-batch-and-exit((and t))
  (if ert-runner-verbose (ert-runner/run-tests-batch-and-exit ert-runn
  (let ((test-files (ert-runner--test-files tests)) (test-helper (f-ex
  ert-runner/run()
  apply(ert-runner/run nil)
  commander--handle-command(nil)
  commander-parse(nil)
  (if commander-parsing-done nil (commander-parse (or commander-args (
  eval-buffer(#<buffer  *load*> nil "/Users/andreaturso/.emacs.d/elisp
  load-with-code-conversion("/Users/andreaturso/.emacs.d/elisp/ede-php
  load("/Users/andreaturso/.emacs.d/elisp/ede-php-autoload/.cask/25.0.
  command-line-1(("-scriptload" "/Users/andreaturso/.emacs.d/elisp/ede
  command-line()
  normal-top-level()

Test ede-php-autoload-composer-find-with-target-dir condition:

    (ert-test-failed
     ((should
       (string= "/Users/andreaturso/.emacs.d/elisp/ede-php-autoload/test/projects/with-composer/vendor/target-dir/target-dir/TargetDir/Component/TheClass.php"
		(ede-php-autoload-find-class-def-file ... "TargetDir\\Component\\TheClass")))
      :form
      (string= "/Users/andreaturso/.emacs.d/elisp/ede-php-autoload/test/projects/with-composer/vendor/target-dir/target-dir/TargetDir/Component/TheClass.php" nil)
      :value nil))

F.......

Ran 14 tests in 0.032 seconds
1 unexpected results:
   FAILED  ede-php-autoload-composer-find-with-target-dir
make: *** [test] Error 1
```

As a temporary measure, and to allow me to carry on playing with the code, I wrote [a PHP script to create a list of cons](https://gist.github.com/trashofmasters/af7ed21e5bad2c8fb562) `(prefix . vendor_dir)` that I use to effectively degenerate ede's PSR-0 autoloader into a classmap autoloader.

With some directions I think I should be able to put together an actual class map loader, so if you don't mind I might open another ticket about this.

**Comment by stevenremot** [comment]
The test failure is totally normal, this is the test case I just wrote for developing of the "target-dir" support, so everything is fine.

If I understand correctly you have some ideas to support class map creation in this project ? Don't hesitate to open a new issue so that we can talk about it. I don't really master composer classmaps so this would be nice if you could put some details in the issue please ;-) .

Regarding this "target-dir" issue, I will work on it this week, first by rewriting the third party packages analysis using the composer lock file, and then by actually using the "target-dir" attribute when present.

**Comment by stevenremot** [comment]
I spent some time fixing it today. Using lock file instead of scanning vendor was really easy. Then I discovered the problem wasn't `target-dir`, but it was the code not supporting namespaces with some depth in autoload spec, like this:

```json
{
  "autoload": {
    "psr-0": {
      "My\\Deep\\Ns\\ : ""
    }
  }
}
```

It should be fixed on the issue's branch, but I will add some more tests before merging to master, to be sure I properly handle this case.

**Comment by trashofmasters** [comment]
@stevenremot I had the feeling that the autoloading problem was partially related to the way the function was matching the only the first part of the prefix.

I had a try myself but the result was far from elegant. You can have a look [here](https://github.com/stevenremot/ede-php-autoload/pull/2)

**Comment by trashofmasters** [comment]
Just tested your latest commit on this branch. All is well!
I can now follow all import statements to their respective class file.

**Comment by stevenremot** [comment]
I'm glad it worked! I added some tests and finally merged it to master.

I close this issue now, feel free to reopen it if there is still a problem.
