### ISSUE TITLE
Feature request: support for completions

### ISSUE THREAD

**Issue by jorissteyn** [stevenremot/ede-php-autoload#5]
It would be very useful if the semanticdb backend supported the `find-tags-for-completion-method`-method. It could create faux tags based on the namespace/path mappings and the directory structure. It shouldn't actually parse any files.

Use cases:

```
new Symfony\Component\C[POINT]
  * User presses C-c , SPC
  * so semantic calls the find-tags-... method
  * ede-php determines the path of Symfony\Component
  * and returns faux tags for every file found in the directory, starting with C
  * perhaps recursively
```

```
new Sym[POINT]
  * User presses C-c , SPC
  * so semantic calls the find-tags-... method
  * ede-php matches the prefix (Sym) with all known namespace prefixes
  * and returns faux tags for the relevant prefixes (Symfony\Component, Symfony\Bridge)
```

```
new S[POINT]
  * A combination of above two cases, so classes in S*\* would be found
```

**Comment by stevenremot** [comment]
That would be a nice addition! I won't have much time the next two weeks but I will work on it right after.

**Comment by jorissteyn** [comment]
Cool, no rush :)

**Comment by stevenremot** [comment]
Hey @jorissteyn,

I implemented the type completion. It has some limitations that should be addressed by the Semantic support in my opinion.

The first one is the contextual information (current namespace, use statements, etc...) that means that `new Sym...` could actually be understood as `new \My\Current\Namespace\Sym...`.

The second one is that when Semantic tries to complete `Symfony\Comp`, if the backslash is a member separator (as I declared it in my CEDET fork), then semantic just assume it can find the tag `Symfony` by itself and use its members for providing completion suggestions. I am not sure about how it should be addressed, but this makes the completion feature for types inefficient when using PHP namespaces... My first guess is that we may try to override the default completion behaviour of Semantic which doesn't really make sense in a language like PHP which relies so much on autoloading. What do you think about it?

Despite theses limitations, is my implementation conform to your functional specifications ? ;-)

**Comment by jorissteyn** [comment]
Nice! I plan on trying this out and getting you some feedback soon.

> then semantic just assume it can find the tag Symfony by itself and use its members for providing completion suggestions

That would only work for require/include style projects. And even then there's some C-like behaviour regarding namespaces that doesn't work well for PHP. I plan to create a separate issue later this week about how to handle namespaces. We'll discuss this further.

**Comment by stevenremot** [comment]
Hey @jorissteyn,

I just realized I did not tell you the work has not been pushed to master, it is on the branch [#5-type-completion-support](https://github.com/stevenremot/ede-php-autoload/compare/%235-type-completion-support), waiting for your validation to be merged. No rush of course :-) .

**Comment by stevenremot** [comment]
Since the issue has not been updated since 3 months, I have merged the branch in master. Don't hesitate to reopen it if there is any problem.
